### ISSUE TITLE
Initial open task list

### ISSUE THREAD

**Issue by mikeshardmind** [unified-moderation-network/salamander#3]
(Sparse initial list, more to be done + describing this...)

- [x] Basic Mod tools
- [ ] Chat cleanup tools
- [ ] Automoderation (Integration with future work on Basalisk)
- [ ] Scheduled events (Integration with serpent)
- [ ] Embedded Messages
- [ ] Tag box
- [x] Role tools

**Comment by mikeshardmind** [comment]
This list needs to evolve into multiple projects, the scope of some of these "small" things is much larger than appropriate to track like this going forward.
